version: "3"
services:
  backend:
    build: ./ruby-app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./ruby-app:/app
    ports:
      - "3000:3000"
  frontend:
    build: ./react-app
    command: npm run start
    volumes:
      - ./react-app:/app
    ports:
      - "3001:3000"
    depends_on:
      - backend
