# Start with the official Node.js Docker image
FROM node:latest

WORKDIR /app

COPY package*.json ./

# Install dependencies
RUN npm install

ENV PATH /app/node_modules/.bin:$PATH

# Copy all files
COPY . .

EXPOSE 3000
